/**
 * Generates app/utils/before-after-orientation.ts: a static map of every
 * before/after image's orientation (portrait | landscape | square), used to
 * decide which images can fill the portrait hero box without bad cropping.
 *
 * Re-run whenever images are added/changed: pnpm exec tsx scripts/gen-before-after-orientation.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import sharp from 'sharp'

const dir = path.join(process.cwd(), 'public', 'img', 'before-after')
const outPath = path.join(process.cwd(), 'app', 'utils', 'before-after-orientation.ts')

const files = fs
	.readdirSync(dir)
	.filter(f => f.endsWith('.webp'))
	.sort()

const map: Record<string, 'portrait' | 'landscape' | 'square'> = {}
for (const f of files) {
	const meta = await sharp(path.join(dir, f)).metadata()
	const ratio = (meta.width ?? 1) / (meta.height ?? 1)
	map[f] = ratio > 1.15 ? 'landscape' : ratio < 0.87 ? 'portrait' : 'square'
}

const entries = Object.entries(map)
	.map(([k, v]) => `\t'${k}': '${v}',`)
	.join('\n')

const contents = `// AUTO-GENERATED by scripts/gen-before-after-orientation.ts — do not edit by hand.
export type ImageOrientation = 'portrait' | 'landscape' | 'square'

export const BEFORE_AFTER_ORIENTATION: Record<string, ImageOrientation> = {
${entries}
}

/**
 * True for images that can fill the portrait hero box via object-cover without
 * destroying them (portrait + square). Wide landscape comparison strips return
 * false so they stay out of the hero and only show in the gallery.
 */
export function isHeroFillImage(src: string): boolean {
	const file = src.split('/').pop() ?? ''
	const orientation = BEFORE_AFTER_ORIENTATION[file]
	return orientation === 'portrait' || orientation === 'square'
}
`

fs.writeFileSync(outPath, contents)
console.log(`wrote ${entries.split('\n').length} entries to ${path.relative(process.cwd(), outPath)}`)
